### ISSUE TITLE
Recipe compile error

### ISSUE THREAD

**Issue by kviknaMedical** [sous-chefs/remote_install#11]
I would like to use this cookbook to download and install software to Ubuntu and Windows OS.
On a test environment, these commands were used:
berks upload --no-ssl-verify
knife ssh 'role:web' 'sudo chef-client' --ssh-user xxxx --ssh-password 'xxxxxx' --attribute ipaddress
---But encountered the error shown below
--------------------
192.168.20.180 Installing Cookbook Gems:
192.168.20.180 Compiling Cookbooks...
192.168.20.180 Recipe Compile Error
192.168.20.180 ================================================================================
192.168.20.180
192.168.20.180 Chef::Exceptions::RecipeNotFound
192.168.20.180 --------------------------------
192.168.20.180 could not find recipe default for cookbook remote_install
192.168.20.180
192.168.20.180 System Info:
192.168.20.180 ------------
192.168.20.180 chef_version=13.6.4
192.168.20.180 platform=ubuntu
192.168.20.180 platform_version=16.04
192.168.20.180 ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
192.168.20.180 program_name=chef-client worker: ppid=33825;start=14:17:09;
192.168.20.180 executable=/opt/chef/bin/chef-client
192.168.20.180
192.168.20.180
192.168.20.180 Running handlers:
192.168.20.180 [2017-12-01T14:17:11-08:00] ERROR: Running exception handlers
192.168.20.180 Running handlers complete
192.168.20.180 [2017-12-01T14:17:11-08:00] ERROR: Exception handlers complete
192.168.20.180 Chef Client failed. 0 resources updated in 02 seconds
192.168.20.180 [2017-12-01T14:17:11-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
192.168.20.180 [2017-12-01T14:17:11-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a b
ug report
192.168.20.180 [2017-12-01T14:17:11-08:00] ERROR: could not find recipe default for cookbook remote_install
192.168.20.180 [2017-12-01T14:17:11-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsucces
sfully (exit code 1)

### Cookbook version
[Version of the cookbook where you are encountering the issue]

### Chef-client version
[Version of chef-client in your environment]

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]

### Scenario:
[What you are trying to achieve and you can't?]

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by majormoses** [comment]
I am guessing you add `"recipe[remote_install]"` this is not a recipe but a library only cookbook, check out the [usage](https://github.com/chef-cookbooks/remote_install#usage) for more info.
